package vpu

import chisel3._
import chisel3.util.log2Ceil
import chisel3.iotesters.{ChiselFlatSpec, PeekPokeTester}

import org.chipsalliance.cde.config.Parameters

import freechips.rocketchip.diplomacy.{AddressSet, LazyModule, LazyModuleImp}
import freechips.rocketchip.devices.tilelink.{DevNullParams, TLError}
import freechips.rocketchip.system.DefaultConfig
import freechips.rocketchip.tile.{RocketTileParams, TileKey,
  TileVisibilityNodeKey}
import freechips.rocketchip.tilelink.{TLAdapterNode, TLFragmenter, TLMessages,
  TLRAM, TLXbar}

/** Transparent test-only TileLink tap used to count the requests generated by
  * each DMA direction without reaching into a child's internal diplomacy IO.
  */
private class VpuTLRequestTap(implicit p: Parameters) extends LazyModule {
  private val maxEvents = 64
  val node = TLAdapterNode()

  lazy val module = new Impl
  class Impl extends LazyModuleImp(this) {
    val io = IO(new Bundle {
      val readARequests = Output(UInt(16.W))
      val writeARequests = Output(UInt(16.W))
      val lastReadASize = Output(UInt(8.W))
      val lastWriteASize = Output(UInt(8.W))
      val readDBeats = Output(UInt(16.W))
      val writeDResponses = Output(UInt(16.W))
      val aEventCount = Output(UInt(log2Ceil(maxEvents + 1).W))
      val aEventOpcode = Output(Vec(maxEvents, UInt(3.W)))
      val aEventSize = Output(Vec(maxEvents, UInt(8.W)))
      val aEventSource = Output(Vec(maxEvents, UInt(16.W)))
      val aEventAddress = Output(Vec(maxEvents, UInt(64.W)))
      val aEventData = Output(Vec(maxEvents, UInt(128.W)))
      val aEventMask = Output(Vec(maxEvents, UInt(16.W)))
      val aEventFirst = Output(Vec(maxEvents, Bool()))
      val aEventLast = Output(Vec(maxEvents, Bool()))
      val aEventCycle = Output(Vec(maxEvents, UInt(32.W)))
    })

    require(node.in.size == 1 && node.out.size == 1)
    val (in, edgeIn) = node.in.head
    val (out, _) = node.out.head

    out.a.valid := in.a.valid
    out.a.bits := in.a.bits
    in.a.ready := out.a.ready
    in.d.valid := out.d.valid
    in.d.bits := out.d.bits
    out.d.ready := in.d.ready

    // VPU DMA is an uncached TL-UL client.
    in.b.valid := false.B
    in.b.bits := DontCare
    out.b.ready := true.B
    out.c.valid := false.B
    out.c.bits := DontCare
    in.c.ready := true.B
    out.e.valid := false.B
    out.e.bits := DontCare
    in.e.ready := true.B

    val readARequests = RegInit(0.U(16.W))
    val writeARequests = RegInit(0.U(16.W))
    val lastReadASize = RegInit(0.U(8.W))
    val lastWriteASize = RegInit(0.U(8.W))
    val readDBeats = RegInit(0.U(16.W))
    val writeDResponses = RegInit(0.U(16.W))
    val aIsRead = in.a.bits.opcode === TLMessages.Get
    val aIsWrite = in.a.bits.opcode === TLMessages.PutFullData ||
      in.a.bits.opcode === TLMessages.PutPartialData
    val aFirst = edgeIn.first(in.a)
    val aLast = edgeIn.last(in.a)
    val cycle = RegInit(0.U(32.W))
    cycle := cycle + 1.U

    val aEventCount = RegInit(0.U(log2Ceil(maxEvents + 1).W))
    val aEventOpcode = Reg(Vec(maxEvents, UInt(3.W)))
    val aEventSize = Reg(Vec(maxEvents, UInt(8.W)))
    val aEventSource = Reg(Vec(maxEvents, UInt(16.W)))
    val aEventAddress = Reg(Vec(maxEvents, UInt(64.W)))
    val aEventData = Reg(Vec(maxEvents, UInt(128.W)))
    val aEventMask = Reg(Vec(maxEvents, UInt(16.W)))
    val aEventFirst = Reg(Vec(maxEvents, Bool()))
    val aEventLast = Reg(Vec(maxEvents, Bool()))
    val aEventCycle = Reg(Vec(maxEvents, UInt(32.W)))
    when(in.a.fire) {
      assert(aIsRead || aIsWrite,
        "VPU DMA tap observed an unsupported TileLink request")
      assert(aEventCount < maxEvents.U,
        "VPU DMA tap exhausted its request log")
      aEventOpcode(aEventCount) := in.a.bits.opcode
      aEventSize(aEventCount) := in.a.bits.size
      aEventSource(aEventCount) := in.a.bits.source
      aEventAddress(aEventCount) := in.a.bits.address
      aEventData(aEventCount) := in.a.bits.data
      aEventMask(aEventCount) := in.a.bits.mask
      aEventFirst(aEventCount) := aFirst
      aEventLast(aEventCount) := aLast
      aEventCycle(aEventCount) := cycle
      aEventCount := aEventCount + 1.U
      when(aIsRead) {
        when(aFirst) { readARequests := readARequests + 1.U }
        lastReadASize := in.a.bits.size
      }.otherwise {
        when(aFirst) { writeARequests := writeARequests + 1.U }
        lastWriteASize := in.a.bits.size
      }
    }
    when(out.d.fire) {
      when(out.d.bits.opcode === TLMessages.AccessAckData) {
        readDBeats := readDBeats + 1.U
      }.elsewhen(out.d.bits.opcode === TLMessages.AccessAck) {
        writeDResponses := writeDResponses + 1.U
      }
    }

    io.readARequests := readARequests
    io.writeARequests := writeARequests
    io.lastReadASize := lastReadASize
    io.lastWriteASize := lastWriteASize
    io.readDBeats := readDBeats
    io.writeDResponses := writeDResponses
    io.aEventCount := aEventCount
    io.aEventOpcode := aEventOpcode
    io.aEventSize := aEventSize
    io.aEventSource := aEventSource
    io.aEventAddress := aEventAddress
    io.aEventData := aEventData
    io.aEventMask := aEventMask
    io.aEventFirst := aEventFirst
    io.aEventLast := aEventLast
    io.aEventCycle := aEventCycle
  }
}

private class VpuTLMemoryHarness(val vpuParams: VpuParams)
    (implicit p: Parameters) extends LazyModule {
  // VpuTLMemory normally lives under BaseTile, which supplies these two
  // legacy compatibility keys.  Recreate that narrow context for this
  // standalone diplomatic unit test and put the visibility node in the same
  // negotiated path so HasCoreParameters sees the real address width.
  val visibilityNode = freechips.rocketchip.tilelink.TLEphemeralNode()
  private val dutParameters = p.alterMap(Map(
    TileKey -> RocketTileParams(),
    TileVisibilityNodeKey -> visibilityNode))
  val dut = LazyModule(new VpuTLMemory(vpuParams)(dutParameters))
  val tap = LazyModule(new VpuTLRequestTap()(dutParameters))
  val ram = LazyModule(new TLRAM(AddressSet(0x0, 0xffff), beatBytes = 16))
  val error = LazyModule(new TLError(DevNullParams(
    address = Seq(AddressSet(0x10000, 0xffff)),
    maxAtomic = 8,
    maxTransfer = 64), beatBytes = 16))
  private val xbar = TLXbar()
  ram.node := TLFragmenter(16, 64) := xbar
  error.node := xbar
  xbar := tap.node := visibilityNode := dut.idNode

  lazy val module = new VpuTLMemoryHarnessImp(this)
}

private class VpuTLMemoryHarnessImp(outer: VpuTLMemoryHarness)
    extends LazyModuleImp(outer) {
  val io = IO(new Bundle {
    val dma = Flipped(new VpuDmaIO(outer.vpuParams))
    val busy = Output(Bool())
    val fault = Output(Bool())
    val readARequests = Output(UInt(16.W))
    val writeARequests = Output(UInt(16.W))
    val lastReadASize = Output(UInt(8.W))
    val lastWriteASize = Output(UInt(8.W))
    val readDBeats = Output(UInt(16.W))
    val writeDResponses = Output(UInt(16.W))
    val aEventCount = Output(UInt(7.W))
    val aEventOpcode = Output(Vec(64, UInt(3.W)))
    val aEventSize = Output(Vec(64, UInt(8.W)))
    val aEventSource = Output(Vec(64, UInt(16.W)))
    val aEventAddress = Output(Vec(64, UInt(64.W)))
    val aEventData = Output(Vec(64, UInt(128.W)))
    val aEventMask = Output(Vec(64, UInt(16.W)))
    val aEventFirst = Output(Vec(64, Bool()))
    val aEventLast = Output(Vec(64, Bool()))
    val aEventCycle = Output(Vec(64, UInt(32.W)))
  })

  outer.dut.module.io.dma <> io.dma
  io.busy := outer.dut.module.io.busy
  io.fault := outer.dut.module.io.fault

  io.readARequests := outer.tap.module.io.readARequests
  io.writeARequests := outer.tap.module.io.writeARequests
  io.lastReadASize := outer.tap.module.io.lastReadASize
  io.lastWriteASize := outer.tap.module.io.lastWriteASize
  io.readDBeats := outer.tap.module.io.readDBeats
  io.writeDResponses := outer.tap.module.io.writeDResponses
  io.aEventCount := outer.tap.module.io.aEventCount
  io.aEventOpcode := outer.tap.module.io.aEventOpcode
  io.aEventSize := outer.tap.module.io.aEventSize
  io.aEventSource := outer.tap.module.io.aEventSource
  io.aEventAddress := outer.tap.module.io.aEventAddress
  io.aEventData := outer.tap.module.io.aEventData
  io.aEventMask := outer.tap.module.io.aEventMask
  io.aEventFirst := outer.tap.module.io.aEventFirst
  io.aEventLast := outer.tap.module.io.aEventLast
  io.aEventCycle := outer.tap.module.io.aEventCycle

  // Tests run translations in bare/M mode. PTW requests are nevertheless
  // accepted and all response/CSR inputs are tied deterministically.
  outer.dut.module.io.ptw.req.ready := true.B
  outer.dut.module.io.ptw.resp.valid := false.B
  outer.dut.module.io.ptw.resp.bits :=
    0.U.asTypeOf(outer.dut.module.io.ptw.resp.bits)
  outer.dut.module.io.ptw.ptbr :=
    0.U.asTypeOf(outer.dut.module.io.ptw.ptbr)
  outer.dut.module.io.ptw.hgatp :=
    0.U.asTypeOf(outer.dut.module.io.ptw.hgatp)
  outer.dut.module.io.ptw.vsatp :=
    0.U.asTypeOf(outer.dut.module.io.ptw.vsatp)
  outer.dut.module.io.ptw.status :=
    0.U.asTypeOf(outer.dut.module.io.ptw.status)
  outer.dut.module.io.ptw.hstatus :=
    0.U.asTypeOf(outer.dut.module.io.ptw.hstatus)
  outer.dut.module.io.ptw.gstatus :=
    0.U.asTypeOf(outer.dut.module.io.ptw.gstatus)
  outer.dut.module.io.ptw.pmp :=
    0.U.asTypeOf(outer.dut.module.io.ptw.pmp)
  outer.dut.module.io.ptw.customCSRs :=
    0.U.asTypeOf(outer.dut.module.io.ptw.customCSRs)
}

private class VpuTLMemoryTester(c: VpuTLMemoryHarnessImp, p: VpuParams)
    extends PeekPokeTester(c) {
  poke(c.io.dma.readDescriptor.valid, 0)
  poke(c.io.dma.readDescriptor.bits.commandTag, 0)
  poke(c.io.dma.readDescriptor.bits.rowCount, 0)
  poke(c.io.dma.readDescriptor.bits.hostStrideBytes, 0)
  poke(c.io.dma.readData.ready, 1)
  poke(c.io.dma.writeDescriptor.valid, 0)
  poke(c.io.dma.writeDescriptor.bits.commandTag, 0)
  poke(c.io.dma.writeDescriptor.bits.rowCount, 0)
  poke(c.io.dma.writeDescriptor.bits.hostStrideBytes, 0)
  poke(c.io.dma.writeData.valid, 0)
  poke(c.io.dma.writeData.bits.commandTag, 0)
  poke(c.io.dma.writeCompletion.ready, 0)
  poke(c.io.dma.clearFault, 0)
  step(5)

  def descriptorStatus(write: Boolean): Unit = {
    val status = if (write) c.io.dma.writeDescriptor.bits.status
      else c.io.dma.readDescriptor.bits.status
    poke(status.dprv, 3)
    poke(status.prv, 3)
  }

  def writeDescriptor(address: BigInt, count: Int,
      spadElement: Int = 0, commandTag: Int = 0,
      rowCount: Int = 0, hostStrideBytes: BigInt = 0): Unit = {
    poke(c.io.dma.writeDescriptor.bits.vaddr, address)
    poke(c.io.dma.writeDescriptor.bits.spadElement, spadElement)
    poke(c.io.dma.writeDescriptor.bits.elementCount, count)
    poke(c.io.dma.writeDescriptor.bits.commandTag, commandTag)
    poke(c.io.dma.writeDescriptor.bits.rowCount, rowCount)
    poke(c.io.dma.writeDescriptor.bits.hostStrideBytes, hostStrideBytes)
    descriptorStatus(write = true)
    poke(c.io.dma.writeDescriptor.valid, 1)
    var timeout = 100
    while (peek(c.io.dma.writeDescriptor.ready) == 0 && timeout > 0) {
      step(1); timeout -= 1
    }
    assert(timeout > 0, "write descriptor timed out")
    step(1)
    poke(c.io.dma.writeDescriptor.valid, 0)
  }

  def writeBeat(data: BigInt, last: Boolean = true,
      spadElement: Int = 0, elementMask: Int = 0xf,
      commandTag: Int = 0): Unit = {
    poke(c.io.dma.writeData.bits.data, data)
    poke(c.io.dma.writeData.bits.elementMask, elementMask)
    poke(c.io.dma.writeData.bits.spadElement, spadElement)
    poke(c.io.dma.writeData.bits.commandTag, commandTag)
    poke(c.io.dma.writeData.bits.last, last)
    poke(c.io.dma.writeData.valid, 1)
    var timeout = 100
    while (peek(c.io.dma.writeData.ready) == 0 && timeout > 0) {
      step(1); timeout -= 1
    }
    assert(timeout > 0, "write data timed out")
    step(1)
    poke(c.io.dma.writeData.valid, 0)
  }

  def waitWriteCompletion(expectError: Boolean,
      commandTag: Int = 0): Unit = {
    var timeout = 200
    while (peek(c.io.dma.writeCompletion.valid) == 0 && timeout > 0) {
      step(1); timeout -= 1
    }
    assert(timeout > 0, "write completion timed out")
    val observedError = peek(c.io.dma.writeCompletion.bits.error)
    assert(peek(c.io.dma.writeCompletion.bits.commandTag) == commandTag,
      s"write completion returned the wrong command tag")
    assert(observedError == (if (expectError) 1 else 0),
      s"unexpected completion: error=$observedError " +
        s"cause=${peek(c.io.dma.writeCompletion.bits.fault.cause)} " +
        s"vaddr=0x${peek(c.io.dma.writeCompletion.bits.fault.vaddr).toString(16)}")
  }

  // The RAM only covers [0, 64 KiB). Its first invalid byte must report an
  // access/store fault and block all subsequent descriptor admission. Keep
  // the producer stream open across the fault: the writer must drain through
  // `last`, but must not claim completion before that final beat arrives.
  val badAddress = BigInt(0x10000)
  writeDescriptor(badAddress, 20)
  val badLine = Seq(
    BigInt("44332211aabbccdd0123456789abcdef", 16),
    BigInt("ffeeddccbbaa99887766554433221100", 16),
    BigInt("0123456789abcdeffedcba9876543210", 16),
    BigInt("89abcdef0123456776543210fedcba98", 16))
  for (i <- badLine.indices) {
    writeBeat(badLine(i), last = false, spadElement = 4 * i)
  }
  var faultTimeout = 100
  while (peek(c.io.dma.halted) == 0 && faultTimeout > 0) {
    step(1); faultTimeout -= 1
  }
  assert(faultTimeout > 0, "write access fault did not halt admission")
  assert(peek(c.io.dma.writeCompletion.valid) == 0,
    "writer completed before draining the producer through last")
  writeBeat(BigInt("00112233445566778899aabbccddeeff", 16),
    last = true, spadElement = 16)
  waitWriteCompletion(expectError = true)
  assert(peek(c.io.dma.writeCompletion.bits.fault.vaddr) == badAddress)
  assert(peek(c.io.dma.writeCompletion.bits.fault.cause) == VpuDmaFaultCause.Access)
  assert(peek(c.io.dma.writeCompletion.bits.fault.isWrite) == 1)
  assert(peek(c.io.dma.halted) == 1)

  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  poke(c.io.dma.readDescriptor.bits.vaddr, 0x2104)
  poke(c.io.dma.readDescriptor.bits.spadElement, 0)
  poke(c.io.dma.readDescriptor.bits.elementCount, 4)
  descriptorStatus(write = false)
  poke(c.io.dma.readDescriptor.valid, 1)
  step(3)
  assert(peek(c.io.dma.readDescriptor.ready) == 0,
    "fault-halted wrapper admitted a new descriptor")
  poke(c.io.dma.readDescriptor.valid, 0)

  // Clearing after the completion drains must invalidate the FrontendTLB and
  // release admission without resetting either TL state machine.
  poke(c.io.dma.clearFault, 1)
  var clearTimeout = 50
  while (peek(c.io.dma.clearFaultDone) == 0 && clearTimeout > 0) {
    step(1); clearTimeout -= 1
  }
  assert(clearTimeout > 0, "fault clear did not complete")
  step(1)
  poke(c.io.dma.clearFault, 0)
  var resumeTimeout = 50
  while (peek(c.io.dma.halted) != 0 && resumeTimeout > 0) {
    step(1); resumeTimeout -= 1
  }
  assert(resumeTimeout > 0, "fault halt did not release")

  // Exercise an element-aligned but bus-unaligned round trip which spans a
  // 4 KiB page boundary. A minimum-width aligned-down 16-byte request contains
  // the twelve useful bytes before the boundary, followed by another 16-byte
  // request containing the four-byte tail. Keep the RAM
  // access outside Rocket's reserved debug page [0, 4 KiB).
  val goodAddress = BigInt(0x2ff4)
  val payload = BigInt("44332211aabbccdd0123456789abcdef", 16)
  val unalignedWriteRequestsBefore = peek(c.io.writeARequests)
  writeDescriptor(goodAddress, 4)
  // The descriptor has already fired. Mutating the producer-side privilege
  // now must not affect the writer's translation context.
  poke(c.io.dma.writeDescriptor.bits.status.dprv, 0)
  poke(c.io.dma.writeDescriptor.bits.status.prv, 0)
  writeBeat(payload)
  waitWriteCompletion(expectError = false)
  assert(peek(c.io.writeARequests) - unalignedWriteRequestsBefore == 2,
    "page-crossing +4-byte write did not use two aligned transactions")
  assert(peek(c.io.dma.writeCompletion.bits.fault.cause) == VpuDmaFaultCause.None)
  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  val unalignedReadRequestsBefore = peek(c.io.readARequests)
  poke(c.io.dma.readDescriptor.bits.vaddr, goodAddress)
  poke(c.io.dma.readDescriptor.bits.spadElement, 0)
  poke(c.io.dma.readDescriptor.bits.elementCount, 4)
  descriptorStatus(write = false)
  poke(c.io.dma.readDescriptor.valid, 1)
  var readTimeout = 100
  while (peek(c.io.dma.readDescriptor.ready) == 0 && readTimeout > 0) {
    step(1); readTimeout -= 1
  }
  assert(readTimeout > 0, "read descriptor timed out after recovery")
  step(1)
  poke(c.io.dma.readDescriptor.valid, 0)
  poke(c.io.dma.readDescriptor.bits.status.dprv, 0)
  poke(c.io.dma.readDescriptor.bits.status.prv, 0)

  // The pipelined reader keeps completed cache lines independent so a source
  // can be returned exactly at D-last. A page-split vector may consequently
  // reach the SRAM writer as multiple masked beats instead of being repacked
  // into one bus-width beat. Reconstruct by the tagged absolute SPAD address.
  var readPayload = BigInt(0)
  var readElementMask = 0
  var readLast = false
  while (!readLast) {
    readTimeout = 200
    while (peek(c.io.dma.readData.valid) == 0 && readTimeout > 0) {
      step(1); readTimeout -= 1
    }
    assert(readTimeout > 0, "read data timed out")
    assert(peek(c.io.dma.readData.bits.error) == 0)
    val beatData = peek(c.io.dma.readData.bits.data)
    val beatMask = peek(c.io.dma.readData.bits.elementMask).toInt
    val spadElement = peek(c.io.dma.readData.bits.spadElement).toInt
    for (i <- 0 until p.dmaElementsPerBeat if (beatMask & (1 << i)) != 0) {
      val element = spadElement + i
      assert(element >= 0 && element < 4)
      assert((readElementMask & (1 << element)) == 0,
        s"read returned SPAD element $element twice")
      val value = (beatData >> (i * p.storageBits)) &
        ((BigInt(1) << p.storageBits) - 1)
      readPayload |= value << (element * p.storageBits)
      readElementMask |= 1 << element
    }
    readLast = peek(c.io.dma.readData.bits.last) == 1
    step(1)
  }
  assert(readElementMask == 0xf)
  assert(readPayload == payload)
  assert(peek(c.io.readARequests) - unalignedReadRequestsBefore == 2,
    "page-crossing +4-byte read did not use two aligned transactions")

  // A naturally 16-byte-aligned FP32 vector uses one full 128-bit TL beat.
  // Translation remains byte-sized like Gemmini, while these assertions check
  // that the independently constructed TileLink message retains lgSize=4.
  val alignedAddress = BigInt(0x2200)
  val alignedPayload = BigInt("0123456789abcdeffedcba9876543210", 16)
  val alignedWriteRequestsBefore = peek(c.io.writeARequests)
  writeDescriptor(alignedAddress, 4)
  writeBeat(alignedPayload)
  waitWriteCompletion(expectError = false)
  assert(peek(c.io.writeARequests) - alignedWriteRequestsBefore == 1,
    "16-byte-aligned write did not use one full-width TileLink request")
  assert(peek(c.io.lastWriteASize) == 4,
    "aligned writer TileLink lgSize was not 4 (16 bytes)")
  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  val alignedReadRequestsBefore = peek(c.io.readARequests)
  poke(c.io.dma.readDescriptor.bits.vaddr, alignedAddress)
  poke(c.io.dma.readDescriptor.bits.spadElement, 0)
  poke(c.io.dma.readDescriptor.bits.elementCount, 4)
  descriptorStatus(write = false)
  poke(c.io.dma.readDescriptor.valid, 1)
  readTimeout = 100
  while (peek(c.io.dma.readDescriptor.ready) == 0 && readTimeout > 0) {
    step(1); readTimeout -= 1
  }
  assert(readTimeout > 0, "aligned read descriptor timed out")
  step(1)
  poke(c.io.dma.readDescriptor.valid, 0)

  readTimeout = 200
  while (peek(c.io.dma.readData.valid) == 0 && readTimeout > 0) {
    step(1); readTimeout -= 1
  }
  assert(readTimeout > 0, "aligned read data timed out")
  assert(peek(c.io.dma.readData.bits.error) == 0)
  assert(peek(c.io.dma.readData.bits.last) == 1)
  assert(peek(c.io.dma.readData.bits.elementMask) == 0xf)
  assert(peek(c.io.dma.readData.bits.data) == alignedPayload)
  step(1)
  assert(peek(c.io.readARequests) - alignedReadRequestsBefore == 1,
    "16-byte-aligned read did not use one full-width TileLink request")
  assert(peek(c.io.lastReadASize) == 4,
    "aligned reader TileLink lgSize was not 4 (16 bytes)")

  def packedBytes(first: Int, count: Int = 16): BigInt =
    (0 until count).foldLeft(BigInt(0)) { (acc, i) =>
      acc | (BigInt((first + i) & 0xff) << (8 * i))
    }

  def issueReadDescriptor(address: BigInt, count: Int,
      spadElement: Int = 0, commandTag: Int = 0,
      rowCount: Int = 0, hostStrideBytes: BigInt = 0): Unit = {
    poke(c.io.dma.readDescriptor.bits.vaddr, address)
    poke(c.io.dma.readDescriptor.bits.spadElement, spadElement)
    poke(c.io.dma.readDescriptor.bits.elementCount, count)
    poke(c.io.dma.readDescriptor.bits.commandTag, commandTag)
    poke(c.io.dma.readDescriptor.bits.rowCount, rowCount)
    poke(c.io.dma.readDescriptor.bits.hostStrideBytes, hostStrideBytes)
    descriptorStatus(write = false)
    poke(c.io.dma.readDescriptor.valid, 1)
    var timeout = 200
    while (peek(c.io.dma.readDescriptor.ready) == 0 && timeout > 0) {
      step(1); timeout -= 1
    }
    assert(timeout > 0, "read descriptor timed out")
    step(1)
    poke(c.io.dma.readDescriptor.valid, 0)
  }

  def expectReadBeat(data: BigInt, elementMask: Int, spadElement: Int,
      last: Boolean): Unit = {
    var timeout = 500
    while (peek(c.io.dma.readData.valid) == 0 && timeout > 0) {
      step(1); timeout -= 1
    }
    assert(timeout > 0, "read beat timed out")
    assert(peek(c.io.dma.readData.bits.error) == 0)
    assert(peek(c.io.dma.readData.bits.data) == data,
      s"read data mismatch at VSRAM element $spadElement")
    assert(peek(c.io.dma.readData.bits.elementMask) == elementMask)
    assert(peek(c.io.dma.readData.bits.spadElement) == spadElement)
    assert(peek(c.io.dma.readData.bits.last) == (if (last) 1 else 0))
    poke(c.io.dma.readData.ready, 1)
    step(1)
    poke(c.io.dma.readData.ready, 0)
  }

  def eventCount: Int = peek(c.io.aEventCount).toInt

  def assertConsecutiveEvents(first: Int, count: Int, clue: String): Unit = {
    for (i <- 1 until count) {
      val previous = peek(c.io.aEventCycle(first + i - 1))
      val current = peek(c.io.aEventCycle(first + i))
      assert(current == previous + 1,
        s"$clue inserted an A-channel bubble between beats ${i - 1} and $i")
    }
  }

  def dataMask(byteMask: Int): BigInt =
    (0 until 16).foldLeft(BigInt(0)) { (acc, i) =>
      if (((byteMask >> i) & 1) != 0)
        acc | (BigInt(0xff) << (8 * i))
      else acc
    }

  // A complete aligned cache line is one size=6 transaction. The writer must
  // present its four 128-bit A beats without bubbles and receive one AccessAck;
  // the reader emits one Get and reconstructs the four returned D beats.
  val lineAddress = BigInt(0x2400)
  val linePayload = (0 until 4).map(i => packedBytes(0x20 + 16 * i))
  var firstEvent = eventCount
  val lineWriteRequestsBefore = peek(c.io.writeARequests)
  val lineWriteResponsesBefore = peek(c.io.writeDResponses)
  writeDescriptor(lineAddress, 16)
  for (i <- linePayload.indices) {
    writeBeat(linePayload(i), last = i == linePayload.size - 1,
      spadElement = 4 * i)
  }
  waitWriteCompletion(expectError = false)
  assert(peek(c.io.writeARequests) - lineWriteRequestsBefore == 1,
    "aligned cache-line write did not use one TileLink transaction")
  assert(eventCount - firstEvent == 4,
    "aligned cache-line write did not emit four physical A beats")
  assert(peek(c.io.writeDResponses) - lineWriteResponsesBefore == 1,
    "aligned cache-line write did not complete with one AccessAck")
  val lineSource = peek(c.io.aEventSource(firstEvent))
  for (i <- 0 until 4) {
    assert(peek(c.io.aEventSize(firstEvent + i)) == 6)
    assert(peek(c.io.aEventSource(firstEvent + i)) == lineSource)
    assert(peek(c.io.aEventAddress(firstEvent + i)) == lineAddress)
    assert(peek(c.io.aEventMask(firstEvent + i)) == 0xffff)
    assert(peek(c.io.aEventData(firstEvent + i)) == linePayload(i))
    assert(peek(c.io.aEventFirst(firstEvent + i)) == (if (i == 0) 1 else 0))
    assert(peek(c.io.aEventLast(firstEvent + i)) == (if (i == 3) 1 else 0))
  }
  assertConsecutiveEvents(firstEvent, 4, "aligned cache-line write")
  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  poke(c.io.dma.readData.ready, 0)
  firstEvent = eventCount
  val lineReadRequestsBefore = peek(c.io.readARequests)
  val lineReadBeatsBefore = peek(c.io.readDBeats)
  issueReadDescriptor(lineAddress, 16)
  for (i <- linePayload.indices) {
    expectReadBeat(linePayload(i), 0xf, 4 * i,
      last = i == linePayload.size - 1)
  }
  assert(peek(c.io.readARequests) - lineReadRequestsBefore == 1,
    "aligned cache-line read did not use one TileLink Get")
  assert(eventCount - firstEvent == 1,
    "aligned cache-line read emitted more than one A beat")
  assert(peek(c.io.readDBeats) - lineReadBeatsBefore == 4,
    "aligned cache-line Get did not return four 128-bit D beats")
  assert(peek(c.io.aEventSize(firstEvent)) == 6)
  assert(peek(c.io.aEventAddress(firstEvent)) == lineAddress)
  assert(peek(c.io.aEventFirst(firstEvent)) == 1)
  assert(peek(c.io.aEventLast(firstEvent)) == 1)

  // Sixty useful bytes beginning at +4 fit in one aligned-down cache-line
  // transaction. PutPartial shifts the first twelve bytes into lanes 4..15,
  // carries the remaining bytes over the following beats, and masks only the
  // four bytes preceding the descriptor. The corresponding Get discards those
  // leading bytes and repacks the payload into ordinary VPU stream beats.
  val shiftedAddress = lineAddress + 4
  val shiftedPayload = (0 until 60).map(i => (0x80 + i) & 0xff)
  val shiftedInputBeats = Seq(
    packedBytes(0x80), packedBytes(0x90), packedBytes(0xa0),
    packedBytes(0xb0, 12))
  firstEvent = eventCount
  val shiftedWriteRequestsBefore = peek(c.io.writeARequests)
  writeDescriptor(shiftedAddress, 15)
  for (i <- shiftedInputBeats.indices) {
    writeBeat(shiftedInputBeats(i), last = i == shiftedInputBeats.size - 1,
      spadElement = 4 * i, elementMask = if (i == 3) 0x7 else 0xf)
  }
  waitWriteCompletion(expectError = false)
  assert(peek(c.io.writeARequests) - shiftedWriteRequestsBefore == 1,
    "+4-byte cache-line write was fragmented into multiple transactions")
  assert(eventCount - firstEvent == 4,
    "+4-byte cache-line write did not emit four physical A beats")
  val shiftedSource = peek(c.io.aEventSource(firstEvent))
  val expectedMasks = Seq(0xfff0, 0xffff, 0xffff, 0xffff)
  val expectedBusData = (0 until 4).map { beat =>
    (0 until 16).foldLeft(BigInt(0)) { (acc, lane) =>
      val descriptorByte = beat * 16 + lane - 4
      if (descriptorByte >= 0 && descriptorByte < shiftedPayload.size)
        acc | (BigInt(shiftedPayload(descriptorByte)) << (8 * lane))
      else acc
    }
  }
  for (i <- 0 until 4) {
    val mask = expectedMasks(i)
    assert(peek(c.io.aEventSize(firstEvent + i)) == 6)
    assert(peek(c.io.aEventSource(firstEvent + i)) == shiftedSource)
    assert(peek(c.io.aEventAddress(firstEvent + i)) == lineAddress)
    assert(peek(c.io.aEventMask(firstEvent + i)) == mask)
    assert((peek(c.io.aEventData(firstEvent + i)) & dataMask(mask)) ==
      (expectedBusData(i) & dataMask(mask)))
    assert(peek(c.io.aEventFirst(firstEvent + i)) == (if (i == 0) 1 else 0))
    assert(peek(c.io.aEventLast(firstEvent + i)) == (if (i == 3) 1 else 0))
  }
  assertConsecutiveEvents(firstEvent, 4, "+4-byte cache-line write")
  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  firstEvent = eventCount
  val shiftedReadRequestsBefore = peek(c.io.readARequests)
  issueReadDescriptor(shiftedAddress, 15)
  for (i <- shiftedInputBeats.indices) {
    expectReadBeat(shiftedInputBeats(i), if (i == 3) 0x7 else 0xf,
      4 * i, last = i == shiftedInputBeats.size - 1)
  }
  assert(peek(c.io.readARequests) - shiftedReadRequestsBefore == 1,
    "+4-byte cache-line read was fragmented into multiple Gets")
  assert(eventCount - firstEvent == 1)
  assert(peek(c.io.aEventSize(firstEvent)) == 6)
  assert(peek(c.io.aEventAddress(firstEvent)) == lineAddress)

  // One 2-D command moves three short rows. Host rows are 64 bytes apart,
  // while local rows occupy consecutive architectural VLEN slots. This is the
  // same split used by Gemmini's row counter: stride advances the external
  // address, and the local row number advances the scratchpad address.
  val stridedAddress = BigInt(0x2800)
  val stridedRows = 3
  val stridedRowElements = 4
  val stridedHostStride = BigInt(64)
  val stridedPayload = Seq(
    BigInt("00112233445566778899aabbccddeeff", 16),
    BigInt("102132435465768798a9bacbdcedfe0f", 16),
    BigInt("ffeeddccbbaa99887766554433221100", 16))

  firstEvent = eventCount
  val stridedWriteRequestsBefore = peek(c.io.writeARequests)
  writeDescriptor(stridedAddress, stridedRowElements,
    rowCount = stridedRows, hostStrideBytes = stridedHostStride)
  for (row <- 0 until stridedRows) {
    writeBeat(stridedPayload(row), last = row == stridedRows - 1,
      spadElement = row * p.vLen)
  }
  waitWriteCompletion(expectError = false)
  assert(peek(c.io.writeARequests) - stridedWriteRequestsBefore == stridedRows,
    "2-D strided write did not emit one transaction per row")
  assert(eventCount - firstEvent == stridedRows,
    "2-D strided write emitted an unexpected number of A beats")
  val expectedStridedAddresses = (0 until stridedRows).map { row =>
    stridedAddress + row * stridedHostStride
  }.toSet
  val observedWriteAddresses = (0 until stridedRows).map { event =>
    assert(peek(c.io.aEventSize(firstEvent + event)) == 4,
      "2-D strided write row was not a full 16-byte transaction")
    peek(c.io.aEventAddress(firstEvent + event))
  }.toSet
  assert(observedWriteAddresses == expectedStridedAddresses,
    "2-D strided write did not advance host addresses by hostStrideBytes")
  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  firstEvent = eventCount
  val stridedReadRequestsBefore = peek(c.io.readARequests)
  issueReadDescriptor(stridedAddress, stridedRowElements,
    rowCount = stridedRows, hostStrideBytes = stridedHostStride)
  poke(c.io.dma.readData.ready, 1)
  var observedStridedRows = Map.empty[Int, BigInt]
  var stridedReadTimeout = 1000
  while (observedStridedRows.size < stridedRows && stridedReadTimeout > 0) {
    if (peek(c.io.dma.readData.valid) == 1) {
      assert(peek(c.io.dma.readData.bits.error) == 0)
      assert(peek(c.io.dma.readData.bits.elementMask) == 0xf)
      val localAddress = peek(c.io.dma.readData.bits.spadElement).toInt
      val row = localAddress / p.vLen
      assert(row >= 0 && row < stridedRows && localAddress == row * p.vLen,
        s"2-D read returned an invalid local row address $localAddress")
      assert(!observedStridedRows.contains(row),
        s"2-D read returned local row $row twice")
      assert(peek(c.io.dma.readData.bits.data) == stridedPayload(row),
        s"2-D read payload mismatch in row $row")
      val isLast = peek(c.io.dma.readData.bits.last) == 1
      assert(isLast == (observedStridedRows.size == stridedRows - 1),
        "2-D read last marker did not terminate the complete descriptor")
      observedStridedRows += row -> peek(c.io.dma.readData.bits.data)
    }
    step(1)
    stridedReadTimeout -= 1
  }
  assert(stridedReadTimeout > 0, "2-D strided read timed out")
  poke(c.io.dma.readData.ready, 0)
  assert(observedStridedRows.keySet == (0 until stridedRows).toSet)
  assert(peek(c.io.readARequests) - stridedReadRequestsBefore == stridedRows,
    "2-D strided read did not emit one transaction per row")
  assert(eventCount - firstEvent == stridedRows,
    "2-D strided read emitted an unexpected number of Gets")
  val observedReadAddresses = (0 until stridedRows).map { event =>
    assert(peek(c.io.aEventSize(firstEvent + event)) == 4,
      "2-D strided read row was not a full 16-byte transaction")
    peek(c.io.aEventAddress(firstEvent + event))
  }.toSet
  assert(observedReadAddresses == expectedStridedAddresses,
    "2-D strided read did not advance host addresses by hostStrideBytes")

  // A later host row may fault even though the first row completed. Report the
  // actual failing row address, not the descriptor base or dense local offset.
  val stridedFaultTag = 0
  val stridedFaultBase = BigInt(0xffc0)
  val stridedFaultStride = BigInt(0x80)
  val expectedSecondRowFault = stridedFaultBase + stridedFaultStride
  issueReadDescriptor(stridedFaultBase, stridedRowElements,
    commandTag = stridedFaultTag, rowCount = 2,
    hostStrideBytes = stridedFaultStride)
  poke(c.io.dma.readData.ready, 1)
  var stridedFaultSeen = false
  var stridedFaultTimeout = 1000
  while (!stridedFaultSeen && stridedFaultTimeout > 0) {
    if (peek(c.io.dma.readData.valid) == 1 &&
        peek(c.io.dma.readData.bits.error) == 1) {
      assert(peek(c.io.dma.readData.bits.commandTag) == stridedFaultTag)
      assert(peek(c.io.dma.readData.bits.last) == 1)
      assert(peek(c.io.dma.readData.bits.elementMask) == 0)
      assert(peek(c.io.dma.readData.bits.fault.vaddr) == expectedSecondRowFault,
        "2-D read fault did not identify the failing host row")
      assert(peek(c.io.dma.readData.bits.fault.cause) ==
        VpuDmaFaultCause.Access)
      assert(peek(c.io.dma.readData.bits.fault.isWrite) == 0)
      stridedFaultSeen = true
    }
    step(1)
    stridedFaultTimeout -= 1
  }
  assert(stridedFaultTimeout > 0 && stridedFaultSeen,
    "second-row 2-D read fault did not complete")
  poke(c.io.dma.readData.ready, 0)

  var stridedFaultDrainTimeout = 500
  while (peek(c.io.busy) != 0 && stridedFaultDrainTimeout > 0) {
    step(1); stridedFaultDrainTimeout -= 1
  }
  assert(stridedFaultDrainTimeout > 0,
    "2-D reader did not drain after a later-row fault")
  assert(peek(c.io.dma.halted) == 1)
  poke(c.io.dma.clearFault, 1)
  var stridedFaultClearTimeout = 100
  while (peek(c.io.dma.clearFaultDone) == 0 &&
      stridedFaultClearTimeout > 0) {
    step(1); stridedFaultClearTimeout -= 1
  }
  assert(stridedFaultClearTimeout > 0,
    "2-D later-row fault clear did not complete")
  step(1)
  poke(c.io.dma.clearFault, 0)
  var stridedFaultResumeTimeout = 100
  while (peek(c.io.dma.halted) != 0 && stridedFaultResumeTimeout > 0) {
    step(1); stridedFaultResumeTimeout -= 1
  }
  assert(stridedFaultResumeTimeout > 0,
    "DMA remained halted after clearing the 2-D row fault")

  // A descriptor-sized payload which omits its final marker is a terminal
  // protocol fault.  Recovery must not wait forever for a beat beyond the
  // declared element count.
  val protocolFaultTag = 3
  val protocolFaultAddress = BigInt(0x2600)
  writeDescriptor(protocolFaultAddress, 4,
    commandTag = protocolFaultTag)
  writeBeat(packedBytes(0xd0), last = false,
    commandTag = protocolFaultTag)
  waitWriteCompletion(expectError = true,
    commandTag = protocolFaultTag)
  assert(peek(c.io.dma.writeCompletion.bits.fault.cause) ==
    VpuDmaFaultCause.Protocol)
  assert(peek(c.io.dma.writeCompletion.bits.fault.isWrite) == 1)
  poke(c.io.dma.writeCompletion.ready, 1)
  step(1)
  poke(c.io.dma.writeCompletion.ready, 0)

  poke(c.io.dma.clearFault, 1)
  var protocolClearTimeout = 100
  while (peek(c.io.dma.clearFaultDone) == 0 &&
      protocolClearTimeout > 0) {
    step(1); protocolClearTimeout -= 1
  }
  assert(protocolClearTimeout > 0,
    "writer protocol-fault clear did not complete")
  step(1)
  poke(c.io.dma.clearFault, 0)
  var protocolResumeTimeout = 100
  while (peek(c.io.dma.halted) != 0 && protocolResumeTimeout > 0) {
    step(1); protocolResumeTimeout -= 1
  }
  assert(protocolResumeTimeout > 0,
    "writer remained halted after protocol-fault clear")

  // Keep a second tagged read live when the first read reaches the error
  // manager. The request generator must stop, drain every irrevocable TL
  // transaction and completed line, and emit one terminal completion per
  // accepted command instead of reactivating a discarded queued descriptor.
  val badReadTag = 1
  val youngerReadTag = 2
  issueReadDescriptor(badAddress, p.vLen,
    spadElement = 0, commandTag = badReadTag)
  issueReadDescriptor(lineAddress, p.vLen,
    spadElement = p.vLen, commandTag = youngerReadTag)
  poke(c.io.dma.readData.ready, 1)

  var badReadErrored = false
  var youngerReadTerminated = false
  var readFaultDrainTimeout = 2000
  while ((!badReadErrored || !youngerReadTerminated) &&
      readFaultDrainTimeout > 0) {
    if (peek(c.io.dma.readData.valid) == 1) {
      val tag = peek(c.io.dma.readData.bits.commandTag).toInt
      val error = peek(c.io.dma.readData.bits.error) == 1
      val last = peek(c.io.dma.readData.bits.last) == 1
      if (error) {
        assert(last)
        assert(peek(c.io.dma.readData.bits.elementMask) == 0)
        assert(peek(c.io.dma.readData.bits.fault.vaddr) == badAddress)
        assert(peek(c.io.dma.readData.bits.fault.cause) ==
          VpuDmaFaultCause.Access)
        assert(peek(c.io.dma.readData.bits.fault.isWrite) == 0)
      }
      if (tag == badReadTag && error) { badReadErrored = true }
      if (tag == youngerReadTag && last) {
        assert(error,
          "discarded younger read incorrectly reported successful completion")
        youngerReadTerminated = true
      }
      assert(tag == badReadTag || tag == youngerReadTag,
        s"read-fault drain returned unexpected tag $tag")
    }
    step(1)
    readFaultDrainTimeout -= 1
  }
  assert(readFaultDrainTimeout > 0,
    "tagged read-fault drain deadlocked with a queued descriptor")
  assert(badReadErrored,
    "faulting read did not produce an access-error completion")

  var readerDrainTimeout = 500
  while (peek(c.io.busy) != 0 && readerDrainTimeout > 0) {
    step(1); readerDrainTimeout -= 1
  }
  assert(readerDrainTimeout > 0,
    "reader remained busy after tagged fault completions drained")
  assert(peek(c.io.dma.halted) == 1)

  poke(c.io.dma.clearFault, 1)
  var finalClearTimeout = 100
  while (peek(c.io.dma.clearFaultDone) == 0 && finalClearTimeout > 0) {
    step(1); finalClearTimeout -= 1
  }
  assert(finalClearTimeout > 0,
    "read-fault clear did not complete after queue drain")
  step(1)
  poke(c.io.dma.clearFault, 0)
}

class VpuTLMemorySpec extends ChiselFlatSpec {
  behavior of "VpuTLMemory descriptor context and fault recovery"
  it should "report faults, halt admission, drain-clear the TLB, and resume" in {
    implicit val params: Parameters = (new DefaultConfig).toInstance
    val vp = VpuParams(vLen = 32, nLanes = 4, sfuLanes = 2, vSpadKB = 8)
    chisel3.iotesters.Driver.execute(Array("--backend-name", "verilator",
      "--target-dir", "test_run_dir/vpu-tl-memory"),
      () => LazyModule(new VpuTLMemoryHarness(vp)).module) {
      c => new VpuTLMemoryTester(c, vp)
    } should be (true)
  }

}
